;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="PlayerStates_Idle",NewTagName="PlayerStates")
+GameplayTagRedirects=(OldTagName="Stat.Speed",NewTagName="Stat.MovementSpeed")
+GameplayTagRedirects=(OldTagName="Stat.Attack",NewTagName="Stat.Strength")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="Item.Stat.Uses",DevComment="")
+GameplayTagList=(Tag="PlayerStates",DevComment="")
+GameplayTagList=(Tag="PlayerStates.Combat",DevComment="")
+GameplayTagList=(Tag="PlayerStates.CombatInProgress",DevComment="")
+GameplayTagList=(Tag="PlayerStates.Idle",DevComment="")
+GameplayTagList=(Tag="PlayerStates.Teleport",DevComment="")
+GameplayTagList=(Tag="Stat.AttackSpeed",DevComment="")
+GameplayTagList=(Tag="Stat.CritChance",DevComment="")
+GameplayTagList=(Tag="Stat.CritMultipiler",DevComment="")
+GameplayTagList=(Tag="Stat.Defense",DevComment="")
+GameplayTagList=(Tag="Stat.Health",DevComment="")
+GameplayTagList=(Tag="Stat.MovementSpeed",DevComment="")
+GameplayTagList=(Tag="Stat.Strength",DevComment="")
+GameplayTagList=(Tag="Status.Health.Regain",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Ability.Changed",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Ability.Death",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Ability.EnemyAttack",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Ability.Finisher",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Ability.GunAttack",DevComment="Gun Attack Tag")
+GameplayTagList=(Tag="YH.Combat.Ability.HitReact",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Ability.SwordAttack",DevComment="Sword Attack for GAS")
+GameplayTagList=(Tag="YH.Combat.Ability.SwordFinisher",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Combo.Count.One",DevComment="1st Combo Count")
+GameplayTagList=(Tag="YH.Combat.Combo.Count.Three",DevComment="3rd Combo Count")
+GameplayTagList=(Tag="YH.Combat.Combo.Count.Two",DevComment="2nd Combo Count")
+GameplayTagList=(Tag="YH.Combat.Combo.Finisher.Active",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Combo.Finisher.Ready",DevComment="Finisher Ready Tag")
+GameplayTagList=(Tag="YH.Combat.Event.Death",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Event.EnemyAttack.Heavy",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Event.EnemyAttack.Light",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Event.EnemyAttack.Medium",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Event.Finisher",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Event.GunAttack",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Event.GunFinisher",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Event.HitReact",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Event.SwordAttack",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Event.SwordFinisher",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Hit.Confirmed",DevComment="Tag for when Hit is confirmed")
+GameplayTagList=(Tag="YH.Combat.Hit.Missed",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Notify.HitCheck",DevComment="To Confirm Attack Made Contact")
+GameplayTagList=(Tag="YH.Combat.State.Attacking",DevComment="")
+GameplayTagList=(Tag="YH.Combat.State.Idle",DevComment="")
+GameplayTagList=(Tag="YH.Combat.Weapon.Active.Gun",DevComment="Tag for Active Weapon - Gun")
+GameplayTagList=(Tag="YH.Combat.Weapon.Active.Sword",DevComment="Tag for Active Weapon - Sword")
+GameplayTagList=(Tag="YH.Command.Attack",DevComment="")
+GameplayTagList=(Tag="YH.Command.Focus",DevComment="")
+GameplayTagList=(Tag="YH.Command.Items",DevComment="")
+GameplayTagList=(Tag="YH.Command.Magic",DevComment="")
+GameplayTagList=(Tag="YH.Data.Damage",DevComment="")

